steps:
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "bash"
    args:
      - "script/cloudbuild.sh"
      # BRANCH_NAME is not an environment variable, but a Cloud Build substitution variable.
      # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
      - "$BRANCH_NAME"
